# Generated by Django 5.2.10 on 2026-04-01 08:57

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0005_data_migration_athletes_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', validators=[common.validators.FileSizeValidator(file_size=10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=50, validators=[common.validators.OnlyLetterValidator(message='the country must include only letters!')])),
                ('city', models.CharField(max_length=50, validators=[common.validators.OnlyLetterValidator(message='the city must include only letters!')])),
                ('teams', models.ManyToManyField(related_name='tournaments', to='athletes.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
