# Generated by Django 5.2.10 on 2026-04-04 15:35

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.CharField(max_length=50, validators=[common.validators.OnlyLetterValidator(message='The city must include only letters!')]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='country',
            field=models.CharField(max_length=50, validators=[common.validators.OnlyLetterValidator(message='The country must include only letters!')]),
        ),
    ]
