# Generated by Django 5.2.10 on 2026-02-22 00:12

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3), common.validators.OnlyLetterValidator()]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[common.validators.FileSizeValidator(file_size=10)]),
        ),
    ]
