# Generated by Django 5.2.10 on 2026-02-23 17:49

from django.db import migrations

def seed_initial_coaches(apps, schema_editor):
    Coach = apps.get_model('coaches', 'Coach')
    Club = apps.get_model('clubs', 'Club')

    samurai = Club.objects.filter(name="Samurai").first()
    london = Club.objects.filter(name="London KC").first()
    bushido = Club.objects.filter(name="Bushido").first()
    roma = Club.objects.filter(name="Roma").first()

    initial_coaches = [
        {
            "name": "Qnko Sokolov",
            "gender": "M",
            "birth_date": "1988-02-10",
            "coach_license": "B",
            "club": samurai
        },
        {
            "name": "Miroslav Ivanov",
            "gender": "M",
            "birth_date": "1969-11-29",
            "coach_license": "A",
            "club": london
        },
        {
            "name": "Tanya Dicheva",
            "gender": "F",
            "birth_date": "2000-04-15",
            "coach_license": "C",
            "club": bushido
        },
        {
            "name": "Frederico Chiesa",
            "gender": "M",
            "birth_date": "1995-09-18",
            "coach_license": "D",
            "club": roma
        }
    ]

    for data in initial_coaches:
        if data['club']:
            Coach.objects.update_or_create(
                name=data['name'],
                club=data['club'],
                defaults={
                    'gender': data['gender'],
                    'birth_date': data['birth_date'],
                    'coach_license': data['coach_license']
                }
            )

def remove_initial_coaches(apps, schema_editor):
    Coach = apps.get_model('coaches', 'Coach')
    names = ["Qnko Sokolov", "Miroslav Ivanov", "Tanya Dicheva", "Frederico Chiesa"]
    Coach.objects.filter(name__in=names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_alter_coach_name_alter_coach_photo'),
        ('clubs', '0003_data_migration_clubs'),
    ]

    operations = [
        migrations.RunPython(seed_initial_coaches, reverse_code=remove_initial_coaches),
    ]