# Generated by Django 5.2.10 on 2026-02-09 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('founder_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
