# Generated by Django 5.2.10 on 2026-02-22 00:12

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(max_length=50, validators=[common.validators.OnlyLetterValidator(message='the city must include only letters!')]),
        ),
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.CharField(max_length=50, validators=[common.validators.OnlyLetterValidator(message='the country must include only letters!')]),
        ),
        migrations.AlterField(
            model_name='club',
            name='founder_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3), common.validators.OnlyLetterValidator()]),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=3)]),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[common.validators.FileSizeValidator(file_size=10)]),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_club_name_city'),
        ),
    ]
