# Generated by Django 5.2.10 on 2026-02-23 16:39

from django.db import migrations
from django.utils.text import slugify


def seed_initial_clubs(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')

    initial_clubs = [
        {
            "name": "Samurai",
            "city": "Dobrich",
            "country": "Bulgaria",
            "founder_name": "Dimitar Hristov",
            "photo": "samurai_logo.jpg"
        },
        {
            "name": "London KC",
            "city": "London",
            "country": "United Kingdom",
            "founder_name": "John Smith",
            "photo": "london_logo.jpg"
        },
        {
            "name": "Bushido",
            "city": "Varna",
            "country": "Bulgaria",
            "founder_name": "Qnko Sokolov",
            "photo": "bushido_logo.png"
        },
        {
            'name': 'Roma',
            'city': 'Rome',
            'country': 'Italy',
            'founder_name': 'Gianluca Cavalli',
            "photo": "roma_logo.png"
        }
    ]

    for data in initial_clubs:
        club, created = Club.objects.update_or_create(
            name=data['name'],
            city=data['city'],
            defaults={
                'country': data['country'],
                'founder_name': data['founder_name'],
                'photo': data.get('photo'),
                'slug': slugify(f"{data['name']}-{data['city']}")
            }
        )


def remove_initial_clubs(apps, schema_editor):
    Club = apps.get_model('clubs', 'Club')
    initial_clubs = [
        ("Samurai", "Dobrich"),
        ("London KC", "London"),
        ("Bushido", "Varna"),
        ("Roma", "Rome"),
    ]
    for name, city in initial_clubs:
        Club.objects.filter(name=name, city=city).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_city_alter_club_country_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_initial_clubs, reverse_code=remove_initial_clubs),
    ]
