# Generated by Django 5.2.10 on 2026-02-23 18:12

from django.db import migrations

def seed_data(apps, schema_editor):
    Athlete = apps.get_model('athletes', 'Athlete')
    Team = apps.get_model('athletes', 'Team')
    Club = apps.get_model('clubs', 'Club')

    samurai = Club.objects.filter(name="Samurai").first()
    bushido = Club.objects.filter(name="Bushido").first()

    if not samurai or not bushido:
        return

    athletes_data = [
        {"name": "Ivan Petrov", "gender": "M", "birth_date": "2010-05-12", "belt": "Yellow", "club": samurai},
        {"name": "Maria Georgieva", "gender": "F", "birth_date": "2011-08-20", "belt": "Green", "club": samurai},
        {"name": "Stoyan Dobrev", "gender": "M", "birth_date": "2009-01-15", "belt": "Blue", "club": samurai},
        {"name": "Elena Uzunova", "gender": "F", "birth_date": "2012-03-30", "belt": "White", "club": bushido},
        {"name": "Drago Marinov", "gender": "M", "birth_date": "2010-11-22", "belt": "Orange", "club": bushido},
        {"name": "Nina Koleva", "gender": "F", "birth_date": "2011-06-05", "belt": "Yellow", "club": bushido},
    ]

    created_athletes = []
    for a in athletes_data:
        athlete, _ = Athlete.objects.update_or_create(
            name=a['name'],
            birth_date=a['birth_date'],
            defaults={
                'gender': a['gender'],
                'belt': a['belt'],
                'club': a['club']
            }
        )
        created_athletes.append(athlete)

    teams_data = [
        {"name": "Samurai Junior A", "club": samurai, "members": created_athletes[0:3]},
        {"name": "Bushido Warriors", "club": bushido, "members": created_athletes[3:6]},
    ]

    for t in teams_data:
        team, _ = Team.objects.update_or_create(
            name=t['name'],
            club=t['club']
        )
        team.athletes.set(t['members'])

def remove_data(apps, schema_editor):
    Athlete = apps.get_model('athletes', 'Athlete')
    Team = apps.get_model('athletes', 'Team')

    Team.objects.filter(name__in=["Samurai Junior A", "Bushido Warriors"]).delete()
    Athlete.objects.filter(name__in=["Ivan Petrov", "Maria Georgieva", "Stoyan Dobrev", "Elena Uzunova", "Drago Marinov", "Nina Koleva"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_alter_athlete_name_alter_athlete_photo'),
        ('clubs', '0003_data_migration_clubs'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=remove_data),
    ]